### ISSUE TITLE
Customizing Lock Screen not woking

### ISSUE THREAD

**Issue by Manuel83** [auth0/react-native-auth0#10]
Hello, 

i tried to customize the lock screen. I like to change the language and logo. Unfortunately the config options are not taken in to account.

Best regards,
Manuel

```

lock.show({
      closable: true,
      theme: {
        logo: 'https://avatars3.githubusercontent.com/u/5859486?v=3&s=466',
         primaryColor: 'green'
      },
      languageDictionary: {
          emailInputPlaceholder: "something@youremail.com",
          title: "Log me in"
      }
    }, (err, profile, token) => {
      if (err) {
        console.log(err);
        return;
      }
      this.props.navigator.push({
        name: 'Profile',
        passProps: {
          profile: profile,
          token: token,
        }
      });
    });
```

**Comment by hzalaz** [comment]
They are not since those options are for vanilla js lock and not for react-native lock, and react-native-lock is just a wrapper of our native lock implementation (iOS & Android).

Those customisations should be done for those native lock not for the JS one. Here is an example on how to customise the L&F of Lock https://github.com/auth0/react-native-lock/issues/61#issuecomment-234103048 and the language https://github.com/auth0/react-native-lock/issues/51#issuecomment-224280817.

Also the repository for react-native-lock is https://github.com/auth0/react-native-lock
