### ISSUE TITLE
can we use the linkedin api through the auth0 ?

### ISSUE THREAD

**Issue by alexandrzavalii** [auth0/react-native-auth0#103]
Probably its out of the scope of this package, but if you could point to the right direction I would be very thankful!
I want to be able to use `share` api of linkedin.
which looks something like.
```
     fetch(`https://api.linkedin.com/v1/people/~/shares?oauth2_access_token=${clientToken}&format=json&test=test HTTP/1.1`, {
            method: 'POST',
            headers: {
                'x-li-format': 'json',
                'Host': 'api.linkedin.com',
                'Content-Length': '356',      
                'X-Target-URI':'https://api.linkedin.com',                
                'Connection': 'Keep-Alive',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                "comment": "Check out developer.linkedin.com!",
                "content": {
                  "title": "LinkedIn Developers Resources",
                  "description": "Leverage LinkedIn's APIs to maximize engagement",
                  "submitted-url": "https://developer.linkedin.com",
                  "submitted-image-url": "https://example.com/logo.png"
                },
                "visibility": {
                  "code": "anyone"
                }
              })
        }).then((response) => {
            console.log("RESPONSE FROM FETCH: ", response);
        })
```
I am authenticated like this:
```
        auth0
            .webAuth
            .authorize({ connection: 'linkedin', scope: 'openid email' })
            .then(setSession)
            .catch(reject);
```
The response I get is: `"wrong access token"`.
I also tried instead of `oauth2_access_token` parameter to use ` 'Authorization': 'Bearer ' + clientToken`

I am using id token (JWT) which I receive back from auth0, which has structure(XXX.XXX.XXX) and this is probably wrong.
When I verify this (JWT) on https://jwt.io/ website I get : `"Invalid Signature"`

When I used `oauth2_access_token` from the postman it worked. 

My Client Type is `Native`.
Does this mean that I can only call it from native code?

**Comment by cocojoe** [comment]
Hi @alexandrzavalii, quick clarification on the above. You talk about `fetch(`https://api.linkedin.com/v1/people/~/shares?oauth2_access_token=${clientToken}` works when you use postman.  Where are you getting the `clientToken` value from exactly?

On JWT.io you need to provide the certificate in the **Verify signature** if you want to validate it, otherwise it will say `Invalid Signature`

A little information on [Client Types](https://auth0.com/docs/clients/client-types)

**Comment by alexandrzavalii** [comment]
@cocojoe  I tried using JWT from REST console and it worked. 
It never worked with accessToken I retrieve from the react-native-auth0.
Response: 401 Invalid access token.

**Comment by cocojoe** [comment]
Thanks.

So to call the LinkedIn API you need to use the IdP's (Identity Provider e.g. LinkedIn) `access_token`.

Remember that Auth0 is returning Auth0's `access_token`, there is a doc regarding [Calling an Identity Provider API](https://auth0.com/docs/tutorials/calling-an-external-idp-api).

A colleague created a webtask for this you might want to look at.  Instead of calling the LinkedIn API directly you would call it via the webtask, that will securely access the IdP access_token and perform the API call.  https://github.com/vikasjayaram/ext-idp-api-webtask/tree/master/RS256

**Comment by tej-rana** [comment]
Hi,
I am opening this as the Auth0 document gets access token via Grant Type Client Crediential. The access code obtained is insufficient. Is there a way to use Authorization Flow?

https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin/context
