### ISSUE TITLE
realmLogin "cannot read property 'redirect_uri' of undefined"

### ISSUE THREAD

**Issue by tessalt** [auth0/react-native-auth0#107]
I'm trying to run the example from https://github.com/auth0-samples/auth0-react-native-sample/tree/Embedded/01-Custom-Form and I've followed all the setup instructions. 
When I try to submit the form, I get an access denied error with the message `cannot read property 'redirect_uri' of undefined`. I realize this error is coming from the server and not the react native library, but I'm at a loss for how to debug it... any way I can find out what `undefined` was supposed to be?

**Comment by cocojoe** [comment]
I'll check this later today.

**Comment by tessalt** [comment]
@cocojoe thanks!

**Comment by cocojoe** [comment]
I just checked and sample ran fine for me, I would double check your configuration.  Are you using a `Native` client type in your Auth0 dashboard? It's not specifically mentioned in the README as it presumes you are already familiar with the basics. 

https://auth0.com/docs/quickstart/native/react-native

**Comment by GituBojan** [comment]
Hey,

I have a similar issue. I used passwordRealm to get a accessToken from Auth0 API and I receive the JSON string. Unfortunately it seems that the JSON string is not correctly formated from auth0. The quotes are missing for the identifiers. 

Auth0 response
{
accessToken : " ...."
idToken .: " .... "
..
}

instead of
{
"accessToken" : "....."
"idToken" : "...."
...
}

Thank you for your help.
