### ISSUE TITLE
Signature algorithm is different on passwordRealm

### ISSUE THREAD

**Issue by anderslemke** [auth0/react-native-auth0#115]
I'm trying to implement my own authentication, but run into problems.

When I authenticate with username/password, the `idToken` is signed with RS256, whereas when I use the Lock, it's signed with HS256.

What can I do?

**Comment by cocojoe** [comment]
1. How are you checking this, examples please? 
1. Are you providing an audience in your webAuth call?
1. Is your account set to OIDC? Any account created after June 2017 will be OIDC by default.

**Comment by anderslemke** [comment]
1. I'm checking by copy/pasting the idTokens into jwt.io. And also, my API can't verify the tokens I get from `passwordRealm` but it can verify tokens I get from webAuth. How would you like my examples? Specific JWT's?

2. This is not when I'm using webAuth. This happens when I use `passwordRealm`.

Here is how I call it:
````
auth0
    .auth
    .passwordRealm({
      username: email,
      password: password,
      scope: 'openid kiosk offline_access',
      realm: "Username-Password-Authentication"
    })
````

On another note: It doesn't respect my scopes.

3. No, we're not using OIDC.

**Comment by anderslemke** [comment]
In fact, I would rather use the webAuth, but #114 is pretty much a deal-breaker for this.

**Comment by cocojoe** [comment]
Password-Realm is an OIDC only method, by using it you will switch to OIDC flow. In OIDC it will always be signed with RS256.  OIDC will not honour invalid claims. I suggest you have a read through this document - https://auth0.com/docs/scopes/current

As you do not have OIDC enabled, WebAuth will use HS256, ideally you want to be using an OIDC Flow. Either enable in client or specify the audience in WebAuth.

I can't really comment on your API setup, would have a read of https://auth0.com/docs/apis

**Comment by rodrijuarez** [comment]
Having the same problem, given that `passwordRealm` is the only method available for authentication, is there anything we can do? Like opening a new method that uses a different signing without using the realm? 

 It'd help a lot to have these kind of issues solved or at least an easy alternative for implementing this in a native way, given that the other libraries have been deprecated in favor of this one

**Comment by rodrijuarez** [comment]
Interesting, this seems also the case for social logins, every one of them is signed with RS256, it seems weird to me that this isn't forced in the web app with the auth0-lock, given that they've the same behaviour and both of them are public clients, or just by having the auth0-lock your device turns out to be a trusted device?

 I also tried forcing this configuration on the Auth0 dashboard (HS256 signing) but it didn't work, as if the social logins and the passwordRealm api on the react library were forcing the RS256 kind of signing meaning that is an untrusted device.

 On the other side, if we add the client secret to our api calls for authentication it'd make the device to become a trusted one, because we give it this private key, but this cannot be a solution given that we'd be compromising the private key.

 Can't we force on the react-native-auth0 library to use the signing or let this library in any way to convert the device on a trusted one as it probably does the auth0-lock? I'd rather move to this library giving that the auth0-lock one is deprecated, but it's resulting a little bit complicated to do so.

**Comment by cocojoe** [comment]
@rodrijuarez A public client may only use RS256, it is a bug in the dashboard (that is being fixed) that it shows both.  A web app is a confidential client, the secret is stored in the backend and (shouldn't be) accessible by the user directly on the front end.

What is your use case that you can't use RS256?

**Comment by rodrijuarez** [comment]
@cocojoe we already have HS256 implemented because we were using react-native-lock and in front-end we're using lock also, and both of them are being signed with HS256, when I wanted to migrate to this library I found this issue of not being able to have the same signing as before. I'd rather not migrate everything now to RS256 and avoid this complexity

**Comment by rodrijuarez** [comment]
Though I still don't understand why the Auth0 lock retrieves HS256 being a public client

**Comment by cocojoe** [comment]
Sorry, I didn't explain that very well.  What I meant was in our Client setup, the `Native Client` type e.g. Mobile. Will force RS256 in OIDC mode.

It is just a signing algorithm, what are you *Actually* doing that is a problem? Are you using the same client for both apps?

**Comment by rodrijuarez** [comment]
No, but if I use RS256 in mobile and HS256 in my webapp I'll have to support both or move everything to RS256, the thing with that, is that with the previous library of lock it didn't force RS256. Anyways I think I'll probably have to force it anyways for using the refresh token
