### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by datvtwakumo** [auth0/react-native-auth0#119]
I want to choose language of auth0 login in browser! How can I do that?

**Comment by cocojoe** [comment]
You can make changes in your Auth0 Dashboard under [Hosted Pages](https://manage.auth0.com/#/login_page)

**Comment by matejukmar** [comment]
Just to explain this a bit further, since it took me some time to figure it out. If you pass language parameter in authorize call:
`auth0.webAuth.authorize({..., language: 'sv'})`

Then on hosted page script the language parameter will be in 
`config.extraParams.language`

And you can pass it as an option when creating Auth0Lock inside hosted script.

**Comment by cocojoe** [comment]
Will have this added to docs.
