### ISSUE TITLE
Https protocol is required by Auth0 in callback url

### ISSUE THREAD

**Issue by ArmanSo** [auth0/react-native-auth0#145]
Right now we are sending ${bundleIdentifier.toLowerCase()} as protocol to Auth0 but in Android we have dots inside the bundleIdentifier and it cause to see the error that redirect URI is not valid.

**Comment by ArmanSo** [comment]
@lbalmaceda this is uri that I'm sending `com.my_app.debug://my_app-test.eu.auth0.com/android/com.my_app.debug/callback`

When I replace it the protocol with https it's start to work.



I checked the android SDK doc, and it's using https beside of ${bundleIdentifier.toLowerCase()}
and also in client part in bottom of input there is not that says: 
"sure to specify the protocol, http:// or https://, otherwise the callback may fail in some cases."

**Comment by ArmanSo** [comment]
I'm removing underline maybe that's the reason I face invalid URI

**Comment by lbalmaceda** [comment]
Yes, that is. Like I said. 
> schemes must be lowercase and begin with a letter and be followed by any other letter, number . - or +

**Comment by ArmanSo** [comment]
t's solved, but isn't better to document this in some where? it's cause misleading

Thanks @lbalmaceda

**Comment by lbalmaceda** [comment]
I'm glad you solved the issue. 🎉 I'll see if I can add it somewhere. However, the `scheme` is part of the [URI specification](https://tools.ietf.org/html/rfc3986#page-17) and that's out the scope of this library. To be honest is the first time I see a package name with an underscore. We chose it because by defining that value globally in your RN project you can use the same value on both the iOS and Android apps. But you can use the value that you want for schemes, it doesn't need to be this bundle identifier. As long as you respect those specifications and whitelist that same URL on the "Callback URLs" setting on the dashboard, you'll be fine 👍
