### ISSUE TITLE
Social login refresh token missing

### ISSUE THREAD

**Issue by anthonyalviz** [auth0/react-native-auth0#147]
When linking a secondary account to a primary account, the refresh token is not persisted in database record. I have used the social login via auth0-js and that process has persisted the refresh token.

## Code
```
let params = {
     connection: platform,
     connection_scope: ['https://www.googleapis.com/auth/fitness.activity.read'],
     scope: 'openid offline_access',
     accessType: 'offline',
     prompt: 'consent'
};

auth0
     .webAuth
     .authorize(params)  // login via social media
            .then(json => {
                this.linkAccount(json.accessToken, platform)
            })
            .catch(error => {
                console.log(error)
     });
```

## Expected Response (auth0-js framework)
```
{  
   "google-oauth2"   =>   {  
      "provider"=> "google-oauth2",
      "access_token"=> "some_token",
      "refresh_token"=> "some_refesh_token",         <--------
      "expires_in"=> 3600,
      "user_id"=> "1",
      "connection"=> "google-oauth2",
      "isSocial"=> true
   }
}
```

## Response
```
{  
   "google-oauth2"   =>   {  
      "provider"=> "google-oauth2",
      "access_token"=> "some_token",
      "expires_in"=> 3600,
      "user_id"=> "1",
      "connection"=> "google-oauth2",
      "isSocial"=> true
   }
}
```

**Comment by lbalmaceda** [comment]
I don't understand the question. Are you sure this is related to this SDK? `react-native-auth0` doesn't have a method to link user accounts AFAIK.

**Comment by anthonyalviz** [comment]
@lbalmaceda I have a backend service that links accounts. In relation to the SDK, when I use the `react-native-auth0` authorize method, the identity that is created _**does not**_ include the refresh token.

**Comment by lbalmaceda** [comment]
I guess you are using an [Auth0 API](https://manage.auth0.com/#/apis) to request valid access_token's for that audience and be able to use them on your backend app. Remember the API should be allowed to generate refresh tokens by checking this setting on the API configuration section.

![image](https://user-images.githubusercontent.com/3900123/38686951-f29de066-3e4b-11e8-8cfc-2856324e8396.png)

In any case, this is not a issue with this SDK but rather a configuration issue on your dashboard. The params that you are sending on the authorize call looks fine (you're including the `offline_access` scope). You might want to ask for that API `audience` too, since you'll definitely need to verify the access_token's on the backend side. If you need further assistance with this configuration feel free to reach us on https://support.auth0.com/.

**Comment by anthonyalviz** [comment]
@lbalmaceda found the underlying issue... 

According to the docs (https://auth0.com/docs/tokens/idp#renew-the-token) the parameter `access_type=offline` is needed in the **authorization URL** to obtain the IdP.

Looking at WebAuth `authorize` method, any param not specified in the `AuthorizeParams` serializer is immediately appended to the _authorizationUrl_. `auth0-js` handles URL param serialization while `react-native-auth0` does not. 

```
auth0
     .webAuth
     .authorize({
         accessType: offline
     })
```

Authorization URL generated in `react-native-auth0`:  http://someurl.com?accessType=offline **<--- will not persist refresh token in auth0 user identities**

Same URL in `auth0-js`:  http://someurl.com?access_type=offline

More of a gotcha and semantics thing... so just a heads up.

Simple fix for future reference:

```
auth0
     .webAuth
     .authorize({
         access_type: offline
     })
```

Cheers!

**Comment by lbalmaceda** [comment]
I thought you were talking about auth0 refresh tokens, you never mentioned the social provider's refresh token. So yes, the docs link you shared is right and you should be passing that extra authentication parameter on the authorize URL. 
The way to achieve this using this SDK would be to pass _any extra authentication parameter_ in the [webauth](https://github.com/auth0/react-native-auth0/blob/master/webauth/index.js#L48) call like you did on the original post. The issue here is that you're passing a camel case version of the parameter you are required to pass as per the docs. The SDKs don't perform any conversion between camel and snake case on the params. Compare both snippets in your comment above and you'll see what I mean.

The right parameter name is `access_type` and not `accessType`.
I'm glad you could find the answer. Cheers. 🎉
