### ISSUE TITLE
[Android] - Callback from magic link doesn't login 

### ISSUE THREAD

**Issue by Genitivo** [auth0/react-native-auth0#152]
After sending the magic link, if you close the auth0 modal or the app the callback of the magic link seems to be not triggered. The app receive the callback link with `state` and `code` inside, but the promise of `auth0.webAuth.authorize` is never call it.

I've figured out that on `onHostResume` method of `A0Auth0Module.java`, the CANCEL_EVENT_DELAY is too short. If you put an higher value seems to work fine, but I don't know how much breakable it is.

![senza titolo](https://user-images.githubusercontent.com/12028509/39933160-7d7cba9c-5542-11e8-9291-750b4dacb28d.gif)

**Comment by lbalmaceda** [comment]
If you're not familiar with Passwordless; it works in 2 steps:
1. Request login with an identifier (email/phone). This will send the code/link-with-code to the user.
2. Use the identifier (email/phone) and the received code. This will finish the sign in and return you the tokens.

The code can be sent either as a code or as a link. In this case, since passwordless needs to be completed on the platform it began it, you'll need to switch to code mode instead and keep the authentication page open when you switch to the email app. This way the widget will prompt you for the code and return the credentials back to you correctly.

Because (2) requires the identifier, there's no way for this SDK to know what you've typed on the Universal Login Page (ULP) form on (1). So, although the magic link redirection is being captured, the SDK is not being able to complete the authentication. A not-secure alternative for this would be for you to code your own UI, make the request to obtain the code and keep the identifier somewhere. Later, you'd use both values to finish it.
