### ISSUE TITLE
WebAuth potential security vulnerability?

### ISSUE THREAD

**Issue by Knight704** [auth0/react-native-auth0#153]
Hello all,
I wonder if my thoughts are correct. Let's take android as an example.

When I register activity to handle redirects, then this could be done also by any malware application. And those application become one of the options in list when redirected. So user could potentially click on wrong one.

Then malware app will have access to redirect query parameters including code. Is this information sufficient for malware app to continue login flow?

**Comment by lbalmaceda** [comment]
Yes, that's true. But that's also why Android provides domain verification since v6.0. You need to add the `auto-verify` attribute in the intent filter of your app's Android Manifest file, and provide a file under the well-known path of your domain. This way, no "choose app" dialog will be shown and instead it will always open your app. You can get more info [here](https://developer.android.com/training/app-links/verify-site-associations).
