### ISSUE TITLE
[Android] Try to select chrome browser by default to fulfil auth0 custom tab intent

### ISSUE THREAD

**Issue by kylemantesso** [auth0/react-native-auth0#200]
### Description

If the user has multiple browsers capable of serving the Android custom tab intent, a bottom menu appears asking the user to select a browser. The SDK should check if Chrome is already installed and just fulfil it with that.

The native Android Auth0 SDK tries to select chrome to fulfil the custom tab intent when opening web auth. This should also be used in the React Native SDK.

See:
https://github.com/auth0/Auth0.Android/blob/8a848f8b6fd14ac36f38d5a951bd8b33e8244bdf/auth0/src/main/java/com/auth0/android/provider/CustomTabsController.java#L165

The React Native SDK should also perform this check, so users do not have to select which browser they wish to use in order to view web auth.

### Prerequisites

* [✅] Did you check the documentation? [Add a link]
* [✅] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [✅] Are you reporting this to the correct repository?
* [❎ ] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version: 1.3.1
- React Native version: 0.57

### Reproduction

1. Install multiple browsers on Android device
2. Open up Auth0 webauth
3. Presented with browser selection bottom menu

![image](https://user-images.githubusercontent.com/5952336/51222123-69a64480-1990-11e9-8d85-b3227ff18928.png)

**Comment by lbalmaceda** [comment]
As commented on your PR I don't think this is an issue. The native implementation is looking for CCT compatible browsers installed in the device. But the first choice is always what the user has selected as a **global** default, we are not changing that. The only scenario in which the Chrome browsers are selected is if there is more than 1 CCT compatible browser and there is no global default browser selected already. The selection should always be up to the user. Either if they want to use CCT or not. 

This that you are sharing on the screenshot above is the expected behavior for any android app.
