### ISSUE TITLE
Execution failed for task ':react-native-auth0:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by ArronJLinton** [auth0/react-native-auth0#232]
I'm using react-native-auth0 and i've been successfully with it in the past with this same project, but as of recent, when I load the project I'm getting the following error.

I'm running on the following versions
- React Native Auth0 - "1.5.0"
- React Native - "0.59.6"

<img width="731" alt="Screen Shot 2019-08-25 at 9 37 18 PM" src="https://user-images.githubusercontent.com/19734850/63665563-b224ac80-c780-11e9-9d8a-2b90dd85e738.png">

**Comment by yojanmorales** [comment]
hey there! any update fo this? I'm running into same issue

**Comment by yojanmorales** [comment]
> I'm using react-native-auth0 and i've been successfully with it in the past with this same project, but as of recent, when I load the project I'm getting the following error.
> 
> I'm running on the following versions
> 
> * React Native Auth0 - "1.5.0"
> * React Native - "0.59.6"
> 
> <img alt="Screen Shot 2019-08-25 at 9 37 18 PM" width="731" src="https://user-images.githubusercontent.com/19734850/63665563-b224ac80-c780-11e9-9d8a-2b90dd85e738.png">

**hey there! any update fo this? I'm running into same issue**

**Comment by theocikos** [comment]
Any updates? Has any of you managed to solve this issue?

**Comment by theocikos** [comment]
> I'm using react-native-auth0 and i've been successfully with it in the past with this same project, but as of recent, when I load the project I'm getting the following error.
> 
> I'm running on the following versions
> 
>     * React Native Auth0 - "1.5.0"
> 
>     * React Native - "0.59.6"
> 
> 
> <img alt="Screen Shot 2019-08-25 at 9 37 18 PM" width="731" src="https://user-images.githubusercontent.com/19734850/63665563-b224ac80-c780-11e9-9d8a-2b90dd85e738.png">

Any updates? Has any of you managed to solve this issue? @ArronJLinton

**Comment by lbalmaceda** [comment]
👋 apologies for missing this issue. Is it still happening with the last SDK version?

**Comment by theocikos** [comment]
> 👋 apologies for missing this issue. Is it still happening with the last SDK version?

Yes i am using the latest version and React Native - "0.59.10"

**Comment by lbalmaceda** [comment]
The output isn't helpful at all. If you re-run it with the flags suggested in the image, do you get anything we can use to debug?

**Comment by theocikos** [comment]
> The output isn't helpful at all. If you re-run it with the flags suggested in the image, do you get anything we can use to debug?

![Screenshot 2020-05-15 at 4 26 29 PM](https://user-images.githubusercontent.com/49213748/82055679-87d99d00-96c9-11ea-89a4-b65faf140adb.png)

This are the errors i get.

**Comment by lbalmaceda** [comment]
That's better!! Thanks. 

The react-native-auth0 SDK version you are using (1.5.0) still makes use of the support libraries to pull the Chrome Custom Tabs dependency. See [here](https://github.com/auth0/react-native-auth0/blob/v1/android/build.gradle#L41). 
The class name imported on the error shown above does exist and is correct. But for some reason, this Chrome Custom Tabs package didn't get installed for you. You might want to try running it with the `--info` or `--debug` flags to see if it tells you the reason.

You can also check if you're importing AndroidX dependencies to your project. Because those and support dependencies can't co-exist without issues. There's actually a newer version of both React Native (0.60.+) and react-native-auth0 (2.+) that has specific support for AndroidX.
