### ISSUE TITLE
Social Connection Caching

### ISSUE THREAD

**Issue by wincod75** [auth0/react-native-auth0#278]
My app offers 3 different social connection options: Facebook, Twitter and Gmail. On the initial use, the user has the ability to log in with the corresponding social connection that they choose. However, once they log in with Gmail Account A, and then when they log out and return to log in again by using Gmail, it doesn't allow them to choose a different Gmail account to log in with, it defaults to the same account previously used, Gmail Account A.

The same happens with Twitter and Facebook. Once you log in with a specific Twitter or Facebook account, it will not let you login with a different account, it will default to that corresponding account forever more, unless you delete the app and reset.

I can log in with each social connection independently: log in with Facebook -> logout, then log in with Twitter -> logout, then log in with Gmail -> logout... this all works perfectly fine because i'm accessing 3 different user accounts. I simply can't change the specific Facebook, Twitter or Gmail account once i've logged in with said account after the first authentication.

**Question**
Is there currently any way to clear the cache for each connection type to allow for various accounts per social connection or is this a feature request?

"react": "16.6.3",
"react-native": "0.59.10",
"react-native-auth0": "1.6.0"

  facebookSignin = () => {
    this.setState({ social: 'facebook'}, function() {
      this.signInExisting();
    });
  }

  twitterSignin = () => {
    this.setState({ social: 'twitter'}, function() {
      this.signInExisting();
    });
  }

  googleSignin = () => {
    this.setState({ social: 'google-oauth2'}, function() {
      this.signInExisting();
    });
  }

  signInExisting = () => {
    loginSocial(this.state.social).then(resp => {
      getMembersPromise(resp).then(res => {
        try {
          AsyncStorage.setItem('userId', res.data.attributes.id);
          if (res == {}) {
            Actions.root();
            return;
          } else {
            Actions.tabbar();
            return;
          }
        } catch(e) {
          throw Error(error);
        }
      });
    });
  };

export function logout() {
    return getToken().then(tok => {
        disableNotifications(tok);
        AsyncStorage.multiRemove(['userId', 'accessToken', 'expiredAt']);
        auth0.webAuth.clearSession().catch(error => console.log(error));
    });
}

**Comment by Widcket** [comment]
@lbalmaceda please evaluate

**Comment by lbalmaceda** [comment]
@wincod75 That's because of "Seamless SSO". The recommendation is to always [log out properly](https://github.com/auth0/react-native-auth0#log-out) before logging in again. There's an option that is called `federated` logout, which would attempt to sign off your provider's account. Note though that this is not supported by every provider, so use at discretion. The way you do federated logout is by sending a [federated=true](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L129) property when calling the `clearSession` function.

I'd try 2 things:
1. The most straightforward solution seems to be sending as an additional param in the [authentication request](https://github.com/auth0/react-native-auth0#log-in), the property `prompt` with value `login`. This should force the Universal Login page to display and prompt for credentials, similar to how it's being done [here](https://community.auth0.com/t/how-to-logout-in-react-native/9046/2). 

2. If that doesn't work, go to the Auth0 Dashboard, enter into tenant settings, go to advanced and turn OFF the "Seamless SSO" option. Make sure to click SAVE. That would make the Universal Login page display a small button like "Last time you logged in with.. -previous account-". Clicking that, would have the same effect as being auto-redirected as you're being redirected today. But there's also a link below it that says "Use a different account" which would take you back to the main Universal Login page, prompting for credentials. 

![image](https://user-images.githubusercontent.com/3900123/74474730-d5552c80-4e84-11ea-8ba8-4c6531c61da9.png)

Hope that solves the issue

**Comment by wincod75** [comment]
Thanks @lbalmaceda I'll give option 1 a try. I took a look at my tenant settings out of curiosity and I already have "Seamless SSO" turned off. I'll follow up when I have a fix in place. Thanks again for the assistance!

**Comment by wincod75** [comment]
@lbalmaceda So, here's my updated code snippets. I added the prompt=select_account, and here's what happens.

Assuming I have logged into my Twitter account and now wish to login to a different account with Gmail, I am prompted with the first screen/image you see below. It shows me my last login with Twitter, if i select "Not Your Account?" I am sent to the second screen/image you see blow.

So, at this point I can select Facebook, Twitter or Gmail. However, the problem still persists. If i click on Twitter, it does not allow me a fresh login, it uses the same authentication from the first attempt. Same thing with Gmail. If I log in with Gmail Account A, logout, then go back to login and select Gmail, it will ask me if the Gmail account listed is accurate (which in this case would be Gmail Account A), but if i select "Not Your Account" and select to login with Gmail (from the list which also includes Facebook and Twitter) it auto selects Gmail Account A, I have no option to enter a different Gmail/Password.

Maybe my snippets below are wrong? Adding prompt=select_account definitely made a difference, but it just pushed the problem to another screen, it didn't resolve. Adding federated -> true didn't seem to do anything so potentially this is my problem?

Thanks in advance!

`export function loginSocial(prompt=select_account, connection, firebase=true) {
    return auth0
        .webAuth
        .authorize({ connection, scope: "openid profile email offline_access" })
        .then(credentials => {
            setToken(credentials);
            if (firebase) {
                setupFirebase();
            }
            return credentials.idToken;

        }).catch(error => {
            throw Error(error);
        });
}

export function logout() {
    //clear out the local
    return getToken().then(tok => {
        disableNotifications(tok);
        AsyncStorage.multiRemove(['userId', 'accessToken', 'expiredAt']);
        auth0
        .webAuth
        .clearSession(options => {
          options.federated = options.federated || true;
        }).catch(error => console.log(error));
    });
}`

<img width="434" alt="Screen Shot 2020-02-14 at 12 36 49 AM" src="https://user-images.githubusercontent.com/15437599/74505001-f9842e00-4ec3-11ea-90e3-1bc136f018cf.png">
<img width="450" alt="Screen Shot 2020-02-14 at 12 36 59 AM" src="https://user-images.githubusercontent.com/15437599/74505007-fb4df180-4ec3-11ea-8569-49a885855979.png">

**Comment by lbalmaceda** [comment]
I think you're not passing correctly the federated parameter on logout, thus, the first account remains logged in. The snippet for logging out should look like this:


```js
auth0.webAuth.clearSession({ federated: true })
   .catch(error => console.log(error));
```

Also, another thing I forgot to mention. If you're passing the connection name on the authorize call, then passing the `prompt=select_account` will only make it show the whole widget as in the last picture attached. This doesn't seem like the behavior you're looking for. I'd give the federated logout a try and roll back to not send the prompt value at all. See if that helps, cheers.

**Comment by wincod75** [comment]
@lbalmaceda Thank for the follow up, unfortunately this made no difference. I don't need the prompt, because as you said I'm passing the connection name before hand, but the federated logout has had no affect on determining accounts. FB, Twitter and Gmail all default back to the original account that I logged in with, even after updating my logout function with your code sample above.

**Comment by lbalmaceda** [comment]
@wincod75 Your snippet has an error. Let me re-cap first: 

You're trying to authenticate with different social providers. When using 1 account on each of them, that works fine. However, when a given provider has more than 1 account listed, once you've authenticated with one, the next time you are not able to choose between them again and you will get logged in into the first one chosen. Is that correct??

Remember that this behavior is **not** the responsibility of this SDK nor Auth0, but of the authentication provider that you are using, i.e. Facebook.

As mentioned earlier when talking about _federated logout_, each provider has different parameters that it would accept when performing things such as log in or log out. In order to fix this, I suggest you focus on a single provider for now until it works as expected and then move on to the next one.

In the case of _Google_, they publish the params that they accept as `prompt` values [here](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters) (scroll to the last row). The value they accept is `prompt=select_account`, which is going to show Google's account picker for the user to select the account to use. So sending that parameter on authentication should trigger this behavior. Can you try that again, please? 

Note that in the last snippet you shared you are passing the prompt param to your own `loginSocial` function but it doesn't use it anywhere. You **must send** this parameter in the `webAuth.authorize` call. Similarly, check how I'm passing the federated option to the `webAuth.clearSession` call.

```js
//Authentication
export function loginSocial(connection, firebase=true) {
  return auth0
    .webAuth
    .authorize({ connection, scope: "openid profile email offline_access", prompt: "select_account" })
    .then(credentials => {
        setToken(credentials);
        if (firebase) {
            setupFirebase();
        }
        return credentials.idToken;
    }).catch(error => {
        throw Error(error);
    });
}

//Logging out
export function logout() {
    //clear out the local
    return getToken().then(tok => {
    disableNotifications(tok);
    AsyncStorage.multiRemove(['userId', 'accessToken', 'expiredAt']);
    auth0
        .webAuth
        .clearSession({ federated: true })
        .catch(error => console.log(error));
    });
}
```

**Comment by wincod75** [comment]
@lbalmaceda Thank you for following up so quickly!

So, yes I am trying to authenticate with different providers, which does work just fine. The problem is if I want to switch accounts; lets say I authenticated with Twitter, and my friend needs to sign into their account with their Twitter, they can not do so because it defaults, without option, to the originally authenticated Twitter account.

I can log in to 3 different accounts just fine: 1 that is authenticated via Facebook, 1 authenticated via Twitter and 1 authenticated via Gmail. I can log out and in to each one with no issues; each different account is pulled and it works great.

I did update my code per your examples above and fortunately I do now see an account selection option for Gmail; I think adding the prompt back in fixed it, in addition to the federated: true.

So, now when I log in with Gmail and log out, then log in again, I am always prompted to either use the last account I logged in with or select a new account, this is perfect!

Unfortunately, for FB and Twitter it's the some old song and dance. So, per your feedback it sounds like this is on FB and Twitter and not this SDK. If this is true, then we can close this one out. Thank you for your help!

**Comment by lbalmaceda** [comment]
Correct! I'm happy it worked for Google. 
Unfortunately for the rest, it's the external provider that needs to offer this feature. For Facebook, it could be that [this](https://developers.facebook.com/docs/facebook-login/reauthentication/) other parameter works to trigger that, but I'm not sure if that is the same. You'll have to check each provider's documentation to get help triggering this scenario.

I'll close this for now but if you run into an SDK issue, feel free to open a new one.
