### ISSUE TITLE
user-is-not-authorized-to-the-audience-for-those-scopes

### ISSUE THREAD

**Issue by laxman-ram-iconnect** [auth0/react-native-auth0#309]
Hi I want to update the user metadata and read it, I do login using passwordless(SMS, email) and using this plugin.

when I try to submit I am getting an error: `user-is-not-authorized-to-the-audience-for-those-scopes` .

auth0.auth
        .loginWithSMS({
          phoneNumber: mobile,
          code: otp,
          scope:
            'read:current_user update:users update:users_app_metadata update:current_user_metadata',
          audience: 'https://[domain].eu.auth0.com/api/v2/',
        })
        .then(credentials => {
            userLoggedIn(credentials);
        })
        .catch(err => {
          this.setLoading(false);
          console.log(err);
        });

Above is the code.

Please help on this.
Thanks

**Comment by laxman-ram-iconnect** [comment]
resolved it, remove audience part and it worked.

**Comment by lbalmaceda** [comment]
👋 Hi, @laxman-ram-iconnect I'm glad you were able to resolve the issue yourself.

The `audience` value is used when you need an access token that works for calling a specific API. The value you are passing above is for calling the Auth0 Management API2. 

The error you see is because Native clients such as a mobile app should NOT request a token with the scopes you added above. If you get a token like that, anyone with it would be able to edit another user's in your database information. The most common use case for a mobile app would be editing the user_metadata or profile of the **current user** to add a bit of information. They have special scopes you might find useful to try. Read more [here](https://auth0.com/docs/migrations/guides/calling-api-with-idtokens#changes-in-scopes).
