### ISSUE TITLE
is checkSession method supported? 

### ISSUE THREAD

**Issue by abolfazlyounesi** [auth0/react-native-auth0#311]

**Comment by lbalmaceda** [comment]
👋 Check session is not available. The SDK only performs the authorization code flow + PKCE. You'd typically keep the access token safely stored and use it while it's valid (e.g. not expired). If it expires, you can request a new one if you have around the refresh token.

Related to https://github.com/auth0/react-native-auth0/issues/296

**Comment by Widcket** [comment]
Going to close this issue, if you have any further inquiries please leave a comment.

**Comment by lhuria94** [comment]
Hi, I have a similar use case, where we want to SSO from web to mobile.
So, internally whenever the mobile app opens, we want to check if the session exists then trigger login.

Is it possible.

**Comment by lbalmaceda** [comment]
@lhuria94 As mentioned before, this is not supported by the SDK. You can either use refresh tokens or launch the `/authorize` page for a new login. If the SSO session is still valid, your app should open right away (I haven't tested). Note on this second approach there's no way to avoid the browser from showing. And it's likely that the redirect gets blocked by the browser app because there's no "user interaction" that could have triggered that redirect call.
