### ISSUE TITLE
Add support for react-native-windows

### ISSUE THREAD

**Issue by marknelissen** [auth0/react-native-auth0#335]
### Describe the problem you'd like to have solved

The current version of react-native-auth0 only supports the default environments of iOS and Android. However, React Native can also be used to produce Windows (UWP) apps, through the use of react-native-windows. Although not part of the base product of React Native, it has become a mature implementation.

### Describe the ideal solution

Ideally, the react-native-auth0 SDK would work equally well on Windows as it does currently on Android and iOS, meaning that except for the initial install configuration impact, the plugin would just work when piloted from the Javascript layer.

## Alternatives and current work-arounds

We currently have a separate login flow in the app for Windows, based on the Auth0.OidcClient.UWP sdk that we pilot through a custom native module. But this does not work as fluently as the Auth flow for the app on Android and iOS.

### Additional context

Before, the react-native-windows implementation was not feature complete with React Native. According to the documentation, it now is fully feature complete, so any elements that are used from React Native (eg. to open the browser Window) should now work, and are thus a reason less to not also support Windows.

**Comment by bandrews** [comment]
I have a need for this feature, too;  Windows is actually the primary target for the react-native app I'm working on, and iOS and Android are secondary...

**Comment by duraz0rz** [comment]
Looks like someone opened #356 to add `react-native-windows` support!

**Comment by lbalmaceda** [comment]
Hi all and apologies for the lack of response 👋  I've raised this feature request for internal discussion the past week, and after a long conversation, we've decided we will not provide support for the Windows platform with this SDK. The main reason being that we don't have a dedicated person today that can maintain this code. I'll proceed to close the related issues/PRs.

**Comment by stmoy** [comment]
👋 - hi @lbalmaceda! My name is Steven and I'm from the React Native for Windows team here at Microsoft. Thank you for reviewing the contribution from @tritao. I wanted to provide a bit more context on this contribution: Microsoft is partnering with Janea Systems to help bootstrap the module ecosystem for React Native for Windows. We identified Auth0 as an important module for RNW apps and worked with @tritao to add a Windows implementation in PR #356. 

We have added Windows support to a bunch of community modules - our tracking board is here: https://github.com/microsoft/react-native-windows/projects/23

Our general philosophy at Microsoft has been to contribute back to the community (rather than forking, etc.) so that we can help work alongside the maintainers and be good community members. We recognize that not every maintainer has a need to support Windows (yet 🤞😉) so our general approach has been that MSFT will continue to support the module in the short term. For example, if bugs are found in the Windows implementation, you can shepherd them to Microsoft so we can take a look/fix/etc. - again, we're making this investment to targeted, important modules because they are critical for React Native for Windows apps to be great (which is good for us, good for you, and good for users).

Given that context and the pipeline to MSFT, would it be possible to reconsider the PR #356? We'd love to work together to get Windows support added to Auth0!

**Comment by kevlil83** [comment]
@stmoy appreciate all the info. The extra context is helpful. We're taking another look at this and will circle back next week. In the near term, would you be willing to hop on a call with me to discuss more about what your team is working on? Would love to dig in and learn more. Thanks! Feel free to reply back here or DM me on Twitter and we can coordinate a time.

**Comment by stmoy** [comment]
@kevlil83 - awesome! Very happy to chat. Lets coordinate on Twitter - is this the right handle? https://twitter.com/lillybrk

**Comment by kevlil83** [comment]
@stmoy thats the one :)
