### ISSUE TITLE
Not able to login with linkedin

### ISSUE THREAD

**Issue by alexandrzavalii** [auth0/react-native-auth0#39]
I am new to auth0.

I am trying to understand the wrapper.
It did work with authlock .But I cannot make it work with this auth0.
```
const auth0 = new Auth0('saddsafas.auth0.com')
                                .authentication('213jjk1j3k12j3k123j')
                                .login('example@gmail.com', 'password', "LinkedIn")
                               .then(credentials => alert(credentials))
                               .catch(error => alert(error));
```
Am I doing something wrong?

<img width="282" alt="screen shot 2017-06-14 at 23 11 21" src="https://user-images.githubusercontent.com/10633451/27156820-d112fac2-5156-11e7-8c9f-2f76371514c8.png">

**Comment by hzalaz** [comment]
Linkedin like any other social provider requires that the credentials be entered in their login page via a browser so that method won't help. You need to use https://github.com/auth0/react-native-auth0#webauth by passing the parameter `connection` with the value `linkedin`. (Check readme instructions on how to set this up and please contact us in https://community.auth0.com
