### ISSUE TITLE
how to get token for different audience

### ISSUE THREAD

**Issue by lutzk** [auth0/react-native-auth0#390]
### Describe the problem you'd like to have solved

in auth0-spa-js to get a token for a different audience i can use `getTokenSilently` with my target audience of the api i want to authenticate

i checked the docs and src but i am not sure how to do that here in `auth0-react-native`
using `webAuth.authorize` always opens the webview

is there a way to get a token for different audience silently with `auth0-react-native`?

### Describe the ideal solution
a method like getTokenSilently is available

**Comment by Widcket** [comment]
Hi @lutzk, it is not possible to get a token for a different audience without logging in again. Are you, per chance, passing the `/userInfo` endpoint as the audience on initial login and then attempting to use your own API as audience? Because if that’s the case, Auth0 always includes the `/userinfo` endpoint as the default audience value; there’s no need to specify it directly, and you could could just pass your own API as the audience value on initial login. Result: you would get a token with 2 audience values: `/userinfo` and your own API. 
That is the only possible case of multiple audience values supported by Auth0.
See https://auth0.com/docs/tokens/access-tokens/get-access-tokens#multiple-audiences
