### ISSUE TITLE
Android: Invalid token specified

### ISSUE THREAD

**Issue by dziter** [auth0/react-native-auth0#396]
### Describe the problem

Hello,

Yesterday, our app was still working really well on both iOS & Android.
As we are close to production, the only change we made was to not rely on developer credentials for the Google Sign In mode. In my opinion, I don't see any link with the current problem which just occurred ONLY on Android. iOS is working fine.

Basically, this piece of code is producing issues:
` try {
    const credentials = await auth0.webAuth.authorize({
      scope: 'openid profile email',
    });
    return credentials;
  } catch (_e) {
    console.log('Failed creating session', _e);
    return null;
  }`
  
 I was always getting: 'Network request failed' but it seems now solved thanks to the last comment of this issue:
 #307 
 
 Now and before the app is crashing, I get:
 
`{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}
WARN  Possible Unhandled Promise Rejection (id: 2):
[InvalidTokenError: Invalid token specified]`

The weird thing too, now I get a pop-in asking me if I want to open the link with my current app when I click on login or signup.
So I am wondering if there is not something broken with the manifestPlaceholders or callbackURL. I double checked on my side, I don't think I made mistakes and the problem just occurred from today.

In the AndroidManifest.xml, I have for the MainActivity:
` <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
              android:host="MY_DOMAIN.eu.auth0.com"
              android:pathPrefix="/android/${applicationId}/callback"
              android:scheme="${applicationId}" />
        </intent-filter>`
        
Please find attached a screenshot:
![Screenshot_1627231296](https://user-images.githubusercontent.com/12848430/126908120-7d91d299-ca25-49d7-8f12-fe66cf73cff4.png)

### What was the expected behavior?

Being able to create an account or to logged in with existing account as I follow the recommendations from:
[https://auth0.com/docs/quickstart/native/react-native/00-login](https://auth0.com/docs/quickstart/native/react-native/00-login)

### Reproduction

Every time on Android when you are just trying to sign up or login doesn't matter if it's the classic email/password or via a social provider like Google for example.

### Environment

- "react-native-auth0": "^2.9.0",
- Android simulator: Pixel 4

Thank you in advance for your help.

**Comment by Widcket** [comment]
Hi @dziter, thanks for raising this. You can quickly check if it's something to do with the manifest placeholders by bypassing them, redeclaring the SDK's `RedirectActivity` in your app's Manifest (intent filter and everything) using static values for the intent filter.

If your problem persists, please check if you're able to reproduce the issue in isolation, eg. in our QuickStart sample app.

**Comment by dziter** [comment]
Hi @Widcket, thanks for your answer.

manifestPlaceHolders are mandatory for me to build the Android version.
But everything is okay since I have deleted the intent filter and let the SDK do the boilerplate by itself I guess.

To be sure, I have used static/hardcoded value for domain and applicationId.
So I am closing this issue.

**Comment by Mr-Fraser** [comment]
I am getting the same issue..

Cody Fraser

Founder & CEO


(+61) 403 650 732

http://www.refrra.io


375 Wickham Terrace, Spring Hill, QLD, 4000
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager
and delete this email from your system. If you are not the intended
recipient you are notified that disclosing, copying, distributing or taking
any action in reliance on the contents of this information is strictly
prohibited. E-mail transmission cannot be guaranteed to be secure or
error-free as information could be intercepted, corrupted, lost, destroyed,
arrive late or incomplete, or contain viruses. The sender therefore does
not accept liability for any errors or omissions in the contents of this
message, which arise as a result of e-mail transmission. If verification is
required please request a hard-copy version. Please note that any views or
opinions presented in this email are solely those of the author and do not
necessarily represent those of the company. Finally, the recipient should
check this email and any attachments for the presence of viruses. The
company accepts no liability for any damage caused by any virus transmitted
by this email.
