### ISSUE TITLE
Missing Auth0 Domain

### ISSUE THREAD

**Issue by bigtiger** [auth0/react-native-auth0#41]
We got the following error:

![2017-06-15 at 7 54 pm](https://user-images.githubusercontent.com/8511/27231541-898f1190-5278-11e7-9176-5ec13581d457.png)

It appears the API changed just before v1.0.0 was released. There wasn't an obvious way that this was communicated and I didn't see any reference to this error elsewhere. If anyone else runs into it this will hopefully point them in the correct direction.

Instantiating Auth0 used to take a string which was the Auth0 domain and now requires an object containing the domain and clientId.

**Comment by hzalaz** [comment]
@bigtiger when we moved from beta to stable we reworked the api of the SDK since a lot of things changed in auth0 since our last release. You can find some info in the [README](https://github.com/auth0/react-native-auth0#usage), our generated [Documentation](http://auth0.github.io/react-native-auth0/index.html) and now we also have a  [CHANGELOG](https://github.com/auth0/react-native-auth0/blob/master/CHANGELOG.md) to better track the changes from now on.
