### ISSUE TITLE
iOS dialog permission

### ISSUE THREAD

**Issue by jalmonacidOA** [auth0/react-native-auth0#425]
### Describe the problem

Every time I try to log into Auth0, iOS shows the permission dialog "App wants to use xxxx.com to sign in". Even after allowing the application to redirect to the browser, log in normally, log out, select log in again, the app asks for permission again, this behavior is repeated every time I reload the application or log out, there is any way to avoid asking for permission every time you want to log in?

### What was the expected behavior?

Don't ask for redirect to web to login when permission has already been granted

### Reproduction

This is a behavior that is repeated from iOS 12 onwards.

### Environment

- **Version of this library used:** 2.10.0
- **Which framework are you using, if applicable:** RN 0.64.0

**Comment by Widcket** [comment]
Hi @jalmonacidOA, thanks for raising this.
That dialog is not created/handled by the SDK, but by the underlying iOS API being used (`ASWebAuthenticationSession`). It is being shown because by default that API will save the auth cookie on the shared Safari cookie jar, which makes SSO possible. 
On iOS 13+ it is possible to enable ephemeral sessions, which will not save the cookie in the shared cookie jar (behaving more like an incognito browser window), which will disable SSO, which means the dialog won't be shown.

For more information about using ephemeral sessions with this SDK, see https://github.com/auth0/react-native-auth0#disable-single-sign-on-ios-13-only

**Comment by jalmonacidOA** [comment]
@Widcket thanks!
