### ISSUE TITLE
The login modal is not popping up when running the app on M1.

### ISSUE THREAD

**Issue by fragilehm** [auth0/react-native-auth0#434]
After pressing login the image below shows up and nothing happens after clicking `Continue`:

<img width="389" alt="Screenshot 2021-12-08 at 15 07 02" src="https://user-images.githubusercontent.com/20160573/145180576-b8a99e8c-77e2-40bb-a996-f576bc14b9c3.png">

Version: `2.10.0`

**Comment by Widcket** [comment]
Hi @fragilehm,

That popup is displayed by default by the underlying Apple API used by the SDK (`ASWebAuthenticationSession`).
See https://github.com/auth0/react-native-auth0#disable-single-sign-on-ios-13-only for more information.
In the future, please complete the issue template instead of removing it. Thanks.

**Comment by fragilehm** [comment]
Thanks for the reply @Widcket but when enabling `ephemeralSession` the previous login sessions will be gone, and on the next login a user will have to re-enter the credentials again, is there a way to keep both options?
