### ISSUE TITLE
Android : App in background reset the auth0 modal state

### ISSUE THREAD

**Issue by Tenember** [auth0/react-native-auth0#438]
### Describe the problem

I'm having issues with our app on Android. When the app is sent on background, then launched again from the home of any Android device, the auth0 modal is closed and his state is reset. 

Bad quality gif explaining the issue : https://giphy.com/gifs/xLa6JwCUhiiTt8JTGE

### What was the expected behavior?

The auth0 modal not closing on app relaunch

### Reproduction

I was able to reproduce the behavior on a clean react native project with version 2.11.0 and on the auth0-react-native-sample with version 2.9.0. I added nothing on the clean and sample app except the necessary configuration explained in the readme.

Clean react native app : https://github.com/aircampus/aircampus-mobile-poc-auth0

### Environment

- **Version of this library used: 2.9.0 and 2.11.0**
- **Which framework are you using, if applicable: react-native, no expo or other boilerplate**
- **Other modules/plugins/libraries that might be involved: A lot on our production app, none on the sample app or the clean app**

**Comment by poovamraj** [comment]
@Tenember Thanks for the analysis, the GIF and the sample app definitely helped us analyze the issue. 

The issue seems to occur only when the app is connected to the development server, without which it works fine. The development server seems to start a new instance of the activity while clicking on the app icon which seems to cause this issue and it shouldn't happen in production. I am closing this issue for now, but please feel free to open it if you have any more doubts or issues regarding this
