### ISSUE TITLE
Missing NativeModule. React Native versions 0.60 and up perform auto-linking

### ISSUE THREAD

**Issue by miladezzat** [auth0/react-native-auth0#475]
Missing NativeModule. React Native versions 0.60 and up perform auto-linking. Please see https://github.com/react-native-community/cli/blob/master/docs/autolinking.md.
at node_modules/react-native-auth0/src/webauth/agent.js:60:8 in Agent#newTransaction
at node_modules/react-native-auth0/src/webauth/index.js:72:11 in WebAuth#authorize
at App.js:19:4 in onLogin
at node_modules/react-native/Libraries/Pressability/Pressability.js:702:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:639:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:520:8 in responderEventHandlers.onResponderRelease

**Comment by poovamraj** [comment]
@miladezzat Can you provide more information on this?

You can use the template which has all the information we require. We especially need information like the RN version you are using and the SDK version as well.

**Comment by fcastaneda9725** [comment]
@poovamraj I'm having the same issue with `"react-native": "0.69.0-rc.6"` and `"react-native-auth0": "^2.13.1"`

**Comment by karimbutt** [comment]
@poovamraj I'm having the same issue on `"react-native": "0.68.1"` and `"react-native-auth0": "^2.13.1"` - however, I'm running RN on MacOS `"react-native-macos": "0.66.57"` - does this lib not work on MacOS? If not, can you give some pointers on how I can take the ios/ files and make them work for React Native on MacOS?

**Comment by karimbutt** [comment]
@fcastaneda9725 absolutely! Here's a demo reproducing the issue: https://github.com/karimbutt/auth0-macos-native-modules-demo (note this does NOT include the native side stuff that needs to be done to catch the auth redirect yet since that part is not relevant for the demo)

`yarn install && cd macos && pod install && yarn start` and then `yarn macos` in another window to start the app and see the error: `Error: Missing NativeModule. React Native versions 0.60 and up perform auto-linking.`

Here's my hunch on why this is happening - I am not sure this can be compatible with MacOS because of this: https://github.com/auth0/react-native-auth0/blob/master/ios/A0Auth0.podspec#L13 - It seems the podspec only targets iOS targets here and no OSX, right?

**Comment by karimbutt** [comment]
@poovamraj  absolutely! Here's a demo reproducing the issue: https://github.com/karimbutt/auth0-macos-native-modules-demo (note this does NOT include the native side stuff that needs to be done to catch the auth redirect yet since that part is not relevant for the demo)

`yarn install && cd macos && pod install && yarn start` and then `yarn macos` in another window to start the app and see the error: `Error: Missing NativeModule. React Native versions 0.60 and up perform auto-linking.`

Here's my hunch on why this is happening - I am not sure this can be compatible with MacOS because of this: https://github.com/auth0/react-native-auth0/blob/master/ios/A0Auth0.podspec#L13 - It seems the podspec only targets iOS targets here and no OSX, right?

@fcastaneda9725 were you using a non iOS target?

**Comment by karimbutt** [comment]
Also, just looking here https://github.com/auth0/react-native-auth0/blob/master/ios/A0Auth0.m - and this is all written for iOS so MacOS can't just be added as a target for the podspec. I'm no Swift / iOS / MacOS pro but stuff like `UIApplication` can't be used for MacOS

**Comment by karimbutt** [comment]
@Widcket thanks! What would you recommend is the best way to get this done in MacOS? Looking at the other Auth0 libs, they all seem to be platform dependent (e.g., some of the JS ones such as React, SPA, and even just JS use `window`). Do I need to roll my own here? If so, do you have examples here of repos where this has been done?

**Comment by Widcket** [comment]
[React Native for macOS](https://github.com/microsoft/react-native-macos) is not an officially supported React Native platform, it's a fork by Microsoft. So I'm afraid you'd have to wrap [Auth0.Swift](https://github.com/auth0/Auth0.swift) (which supports macOS) in a plugin yourself. Or wrap another OpenID-compliant library, like AppAuth.

**Comment by poovamraj** [comment]
@miladezzat Have you tried removing the node modules and trying to install it again?

It seems to have worked in this case - https://github.com/auth0/react-native-auth0/issues/487

**Comment by poovamraj** [comment]
@fcastaneda9725 Can you confirm whether the new release fixes the issue? Also did you try clearing out the `node_modules` folder and retry?

**Comment by miladezzat** [comment]
> @miladezzat Have you tried removing the node modules and trying to install it again?
> 
> It seems to have worked in this case - #487

yes but doesn't work

**Comment by dminkovsky** [comment]
This happens for me with RN 0.69.0. 068.2 is not affected by this problem. Please see my reproduction at https://github.com/auth0-samples/auth0-react-native-sample/issues/68.

**Comment by poovamraj** [comment]
Hi @dminkovsky, @Widcket will be taking a look into this issue and we will get back to you on this. Thanks for raising this!

**Comment by dminkovsky** [comment]
Thank you all. Yes, the very last commit on that example repo seems to have bumped RN to 0.69.0 :) https://github.com/auth0-samples/auth0-react-native-sample/pull/65

**Comment by jedashford** [comment]
When we move the podspec file to the root of the project, the `pod install` works great and the auto linking works. Was a simple change, but you'll need to update the package.json location in the podspec after moving.

move 
`node_modules/react-native-auth0/iOS/A0Auth0.podspec`
to:
`node_modules/react-native-auth0/A0Auth0.podspec`

Then update this line:
`package = JSON.parse(File.read(File.join(__dir__, "./package.json")))`

**Comment by jfspencerAngel** [comment]
Also the react native auto linking docs requires the pod spec to be located in the root directory see: https://github.com/react-native-community/cli/blob/main/docs/autolinking.md#platform-ios

```
This means that all libraries need to ship a Podspec in the root of their folder. Podspec references the native code that your library depends on.
```

**Comment by tickoosunny** [comment]
I am still seeing this issue with version 3.0.0 and 3.2.1 , Is the fix merged in these versions ?

**Comment by elisaado** [comment]
We are also seeing this issue with an Android and iOS project on react native 0.74.4, expo 51.0.28 and node LTS

**Comment by elisaado** [comment]
We have switched to using `expo-auth-session` instead of the Auth0 stack which seems to work well.
