### ISSUE TITLE
Update from beta to 1.0.2, can't login anymore

### ISSUE THREAD

**Issue by mtt87** [auth0/react-native-auth0#48]
Hi, I just updated from the beta version to 1.0.2 and the login doesn't work anymore I think mostly because I don't understand what's related to the `realm`

My previous code that was working:
```js
auth0
      .authentication(CLIENT_ID)
      .login(username, password, 'Username-Password-Authentication', {
        device: 'phone',
        scope: 'openid offline_access',
      })
```

New code
```js
const auth0 = new Auth0({ domain: AUTH0_URL, clientId: CLIENT_ID });
// ...
auth0
      .auth
      .passwordRealm({
        email: username,
        username,
        password,
        realm: 'Username-Password-Authentication',
        scope: 'openid offline_access',
      })
```

I've also tried with `realm: 'database'` but it doesn't work.

I always get `Error: Unauthorized`

😢

**Comment by hzalaz** [comment]
Its using a different endpoint than it was previously (we are slowly deprecating some of them). I think you could get more information on the failed request but I bet its because of the client configuration.

Your client has a list of grant_types and to use it you need to add the following grant "http://auth0.com/oauth/grant-type/password-realm" to your client as detailed [here](https://auth0.com/docs/clients/client-grant-types#edit-the-grant_types-property).

The reason why its not by default is because we recommend AuthN/AuthZ to go though `webAuth` (your tenant hosted login page) using OAuth flows.

**Comment by mtt87** [comment]
@hzalaz thanks for your reply, this is becoming quite complicated to be honest and one of the reason I choose Auth0 was because of simplicity.

I have a custom UI where my users can authenticate with username/password and it's a mobile app built with RN so I don't want to open a webview to do login.

It's not clear to me if it's still possible to do this or not?
Thank you

**Comment by hzalaz** [comment]
It's possible but its not our default since we believe the browser approach is the best way (and simpler)  to get started. You can enable extra auth methods (grant types) if you need them like in your case, during this week we'll add support for doing this in dashboard so it will be easier to enable for you

**Comment by mtt87** [comment]
Thank you, I think then I'll wait for the end of the week for this to be done and for the moment rollback to 1.0.0-beta1 😄

**Comment by hzalaz** [comment]
@mtt87 in Auth0 Dashboard, select your client, click settings -> show advanced settings and find the tab `Grant Types` in the enable the grants you need (check this [guide](https://auth0.com/docs/clients/client-grant-types#edit-the-grant_types-property) for more info but you would need password and maybe MFA).

**Comment by grifotv** [comment]
I'm in the same situation, I'd like to upgrade from `1.0.0-beta1` to the latest `1.1.1` due to this error:

- The method `resetPassword` started to always throw the error `SyntaxError: Unexpected token W in JSON at position 0`, regardless if it's successfully sending the "reset password" email. I believe it's a new error as everything was working fine a few months ago.

@hzalaz Regarding the former `device` param [expected](https://github.com/auth0/react-native-auth0/issues/48#issue-237280771) when logging in with scope `offline_access` in `1.0.0-beta1`, how should it be passed in `1.1.1`?

@mtt87 Did you manage to upgrade at the end?

Thanks!

**Comment by mtt87** [comment]
I didn't upgrade yet, i checked and it was quite difficult (not much info around) and time consuming.

I saw there is a bit more info now so in the next weeks I might decide to do this upgrade.
