### ISSUE TITLE
Android webview login returning error ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by richardgirges** [auth0/react-native-auth0#481]
### Describe the problem
Hello! We have react-native-auth0 working perfectly for iOS. However, we're seeing an odd error when logging in via Android.

Upon initiating `auth0.webAuth.authorize()`, the webview appears and our login domain is loaded. Once you login, the callback fires and we are seeing this error in the webview:
```
"com.myappid" links are blocked
The webpage at com.myappid://login.myappdomain.com/android/com.myappid/callback?code=codegoes here might be temporarily down or it may have moved permanently to a new address.

ERR_UNKNOWN_URL_SCHEME
```

It works perfectly in debug mode. If I was to run a build with `npx react-native run-android`, everything works perfectly. The only time it doesn't work is the `release` variant. Our configuration for debug and release variants is the exact same as far as auth0 goes. 

### Reproduction
1. Login with webview on a react-native android release variant
2. ERR_UNKNOWN_URL_SCHEME is shown in the webview

### Environment
react-native 0.68.1
react-native-auth0 2.13.0
android 12
gradle: com.android.tools.build:gradle:7.0.4
buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31

**Comment by richardgirges** [comment]
This same issue was reported in the auth0-cordova package, but the proposed solution doesn't seem to work: https://github.com/auth0/auth0-cordova/issues/180#issuecomment-968371832

**Comment by poovamraj** [comment]
@richardgirges Can you provide us with the following details
- What is the version of Chrome (assuming that is the browser)? Is it reproducing in other versions as well?
- Can you share the final Merged Manifest for Android (removing any confidential info)?

**Comment by poovamraj** [comment]
Hi @richardgirges can you provide the following details as well

- Merged manifest which can be found under `android/app/build/intermediates/merged_manifest` and `android/app/build/intermediates/merged_manifest/debug`
- Value found for `auth0Domain` under build.gradle of the android app
- If it doesn’t have their auth0 domain, fill it with it and check whether the issue is fixed?

**Comment by poovamraj** [comment]
Hi @richardgirges, in your build.gradle you have set your auth0Domain to your package name instead of the "Domain" value (``manifestPlaceholders = [auth0Domain: "com.mypackage"``) present in Auth0 - it could be something like "name.eu.auth0.com", but I can see your manifest refers to

You can also see there are 2 `RedirectActivity` with 2 different hosts in the manifest. Is there anything configured separately?

**Comment by richardgirges** [comment]
Ah you pointed me directly to the problem. I had misconfigured my buildType configurations and was loading the wrong auth0Domain in the staging release version of the build. Thank you very much! Closing issue.
