### ISSUE TITLE
Delegation is removed from the API

### ISSUE THREAD

**Issue by jozan** [auth0/react-native-auth0#57]
I'm trying to follow this tutorial and adapt it to my React Native app: https://auth0.com/blog/firebase-authentication-with-firebase-3.0-and-auth0-integration/

But it uses `auth0.getDelegationToken` which is not implemented in `react-native-auth0`.

Are there plans to add in in the future or are there workarounds to use Auth0 and Firebase together?

**Comment by hzalaz** [comment]
@jozan its not implemented since using that endpoint is no longer possible for new tenants per https://auth0.com/docs/clients/client-grant-types. If your tenant is able to use it since it was created before 8th June, just make a simple request using fetch and this will be all the parameters needed

```js
var options = {
  id_token : authResult.idToken,
  api : 'firebase',
  scope : 'openid name email displayName',
  target: 'YOUR-AUTH0-CLIENT-ID',
  client_id: 'YOUR-AUTH0-CLIENT-ID',
  grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer'
};
```

More info in https://auth0.com/docs/api/authentication#delegation

**Comment by jozan** [comment]
Thanks for the reply!

Sad news are that yet there are no other options but to use deprecated API which will be deleted at any time and no replacement is provided, for now at least.

**Comment by hzalaz** [comment]
@jozan we are not going to remove the endpoint in the API until we have a replacement for the feature so feel free to use it. Its disabled for new tenants since its not compatible with our latest Auth API that implements OAuth flows.

**Comment by jozan** [comment]
Right, thanks for clarifying! Cheers! :)
