### ISSUE TITLE
getGredentials with 'offline_access' SCOPE returns undefined

### ISSUE THREAD

**Issue by cdanielraducu** [auth0/react-native-auth0#609]
### Describe the problem

Trying to execute this method from auth0 but I get undefined when I'm giving it this SCOPE `offline_access`. Works fine with other scopes. But I am trying go get a refreshToken so that my user gets updated.

### What was the expected behavior?

I've seen this [Issue](https://github.com/auth0/react-native-auth0/issues/572) being solved. So I thought getting a refreshToken would automatically update my user.

### Reproduction

Install the React-Native-Auth0 into an Expo App. Configure the provider and the domain via app.config.ts, setup the Auth0 account an configurations so that sign-in & sign-up works. 
The current scenario for which I need to get my user updated is that after I sign-up I want my email verified. But when the user validates the mail and I return to the app the user from the Auth0Provider is not updated (even after refresh), even after triggering the simple getCredentials.

### Environment

- react-native-auth0: 2.17.0
- Expo

**Comment by poovamraj** [comment]
Hi @cdanielraducu, yes we will be working on providing an option to forcefully updating the user in getCredentials in the next major.

Currently trying to fetch the refresh token wouldn't work for repeated cases since if the scope is same for the previously saved token, we don't fetch it fresh from the server. But this should work if your previous token didn't have `offline_access` scope in it.

That said, can you provide the `customScheme` you are using and also the code snippet on how you call the `getCredentials`.

I have seen this issue happen if `customScheme` is not used in the Expo application. Details on how to use it is in this PR - https://github.com/auth0/react-native-auth0/pull/610

**Comment by poovamraj** [comment]
Hi @cdanielraducu, hope the above answer helps. This example shows how to use custom scheme - https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md#using-custom-scheme-for-web-authentication-redirection

Feel free to comment here and we can reopen this issue if the above answer didn't help.
