### ISSUE TITLE
expo prebuild by default adds forbidden Android `<intent-filter>` to manifest

### ISSUE THREAD

**Issue by jimpala** [auth0/react-native-auth0#653]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Since v2.9, the README has provided a [diff](https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a) of the sample instructing to remove an `<intent-filter>` in the main activity of your Android manifest.

https://github.com/auth0/react-native-auth0/blob/a03fa979a43fe0e8b09c24254ff089277f51897f/README.md?plain=1#L67-L68

The intent filter to remove looks like this:
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data
        android:host="{DOMAIN}"
        android:pathPrefix="/android/${applicationId}/callback"
        android:scheme="${applicationId}" />
</intent-filter>
```

However, Expo's `expo prebuild` command will by default create this intent filter every time if there is a `scheme` property in your `app.json`, which is problematic as from experience it seems to break Android login when included. This looks like the Expo code that creates the prohibited `<intent-filter>` if a scheme is provided:

https://github.com/expo/expo/blob/684194f90503bc71c34c2a4b0dba19532be47846/packages/%40expo/config-plugins/src/android/Scheme.ts#L137-L168

It would be great if this library's config plugin could be amended to remove the prohibited intent filter on `prebuild`, if practical.

### Reproduction

Repro from following steps below: https://github.com/jimpala/auth0-react-native-sample 

1. Add a `scheme` field to your `app.json`.
2. Run `expo prebuild --no-install`
3. Expo will create the main activity `<intent-filter>` prohibited by `react-native-auth0` by default

### Additional context

Could potentially be solved using `withAndroidManifest` in the repo's config plugin to remove the intent filter.

### react-native-auth0 version

2.17.4

### React Native version

0.71.8

### Expo version

48.0.18

### Platform

Android

### Platform version(s)

n/a

**Comment by poovamraj** [comment]
@jimpala We are closing this as we cannot find the issue here. Feel free to comment here and we can reopen it

**Comment by tavvy** [comment]
@poovamraj sorry to revive a very old thread, but I have the same question.

I am trying to debug why we are having random login failures in our production expo react native android application.
I have been looking into the source code at https://github.com/auth0/react-native-auth0/tree/v4.6.0?tab=readme-ov-file we are using the latest stable version 4.6.0

In the docs it is not clear if an expo project should follow the setup provided here: https://github.com/auth0/react-native-auth0/tree/v4.6.0?tab=readme-ov-file#android

It is also not clear if we should have a Redirect Intent filter for our android app.

The docs suggest you should NOT need a redirect intent filter for versions 2.9.0+ however the expo plugin will automatically add this intent filter (as you pointed out in this issue with your [link](https://github.com/jimpala/auth0-react-native-sample/blob/master/00-Login-Expo/android/app/src/main/AndroidManifest.xml#L25)). Going by the project docs this is **incorrect** as highlighted by the original poster.

If it is not suggested to add the intent filter, then why does the expo plugin add it? Why does the expo plugin also NOT perform the recommended setup like the manifestPlaceholders setting. Is it because this should be manually done? or it should not be done at all with expo?

Its not clear to me if we have the app misconfigured or not, and if that is the reason we have failed logins that appear to hang at the point of redirect back into the app.
