### ISSUE TITLE
PasswordRealm scope not applied

### ISSUE THREAD

**Issue by archieherbias** [auth0/react-native-auth0#76]
I can't change the scope in the `passwordRealm`. I tried to decode the `idToken` and the scopes I defined in the `passwordRealm` is not applied . I's using this code:

```
import Auth0 from 'react-native-auth0';

export default class AuthService {
	constructor(domain, clientId) {
		this.auth0 = new Auth0({
			domain,
			clientId,
		});

		this.login = this.login.bind(this);
		this.getUserInfo = this.getUserInfo.bind(this);
	}

	login(username, password) {
		return this.auth0.auth.passwordRealm({
			username,
			password,
			realm: 'myConnection',
			scope: 'openid scopes role access name',
		});
	}

	getUserInfo(accessToken) {
		return this.auth0.auth.userInfo({ token: accessToken });
	}
}
```

When I console log the response of the `getUserInfo` the scope is this `openid profile email address phone` which I expected to be `openid scopes role access name`.

Is there another configuration that I need to do for this?

**Comment by cocojoe** [comment]
@archieherbias please take a look at https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims

In the dashboard you can add a `Rule` to add custom scopes for a connection.

Let's look at adding `role` information to the id_token, in this example I have it in my `app_metadata`

```js
function (user, context, callback) {
  
  if (context.idToken) {
    // You could use app_metadata or any other source for permission data
    // IMPORTANT: The claim name needs to use an HTTP-based namespace
    context.idToken["https://example.com/roles"] = user.app_metadata.roles; 
  }
  
  callback(null, user, context);
}
```

Once you decode the id_token JWT it will be presented as a custom claim:

```ruby
...
"https://example.com/roles": [
    "admin"
  ]
```

**Comment by archieherbias** [comment]
@cocojoe yeah it was setup already in the dashboard to add new `Rule`. It is working when using the auth0 for the web.

Another case is that when I removed the `openid` in the scope, all of the user info will be in the payload of `getUserInfo` but the problem now is that there is no `idToken` already on the response of the `passwordRealm`. I need the `idToken` for other processes.

**Comment by archieherbias** [comment]
I got a new information. It seems I just misconfigured the AndroidManifest.xml,
I accidentally put it in the application and not in activity :` android:launchMode="singleTask"`

The scope can now be applied but there is a new problem. I tried to use this scope `openid access scopes email profile role` but it seems `openid`, `email` and `profile` only are included in the payload when I decoded the `id_token` in jwt.

Does this seem to be an auth0 configuration problem?

**Comment by cocojoe** [comment]
You will not receive an `id_token` if you don't specify `openid` as a scope 😄 

It's not clear to me what you are doing exactly as there are multiple things going on since your original post and a lack of debug information and no information on your rules etc. GH issues are ideally for raising issues with the SDK itself.

You have [standard claims](https://auth0.com/docs/scopes/current#example-asking-for-standard-claims) you can ask for in `scope` and if you add custom claims via rules they will appear in both the `id_token` and `access_token` automatically. You don't need to ask for them in `scope`.

So if you find a problem here and can show us some logs that show some kind of unexpected behaviour then please raise another issue.

If you need more detailed integration help please get in touch via https://support.auth0.com/

Thanks
