### ISSUE TITLE
Delegation and refreshToken usage

### ISSUE THREAD

**Issue by vzhen** [auth0/react-native-auth0#9]
I'm using 0.0.1 and seems like 1.0.0 has changed delegation method.
Could you provide those usages?

About refreshToken()
I haven't test it yet but i had look in the code, in [line 139](https://github.com/auth0/react-native-auth0/blob/master/authentication/api.js#L139), it hard-coded third argument to 'app'. 
I'm using firebase, should it be an options there?

**Comment by hzalaz** [comment]
Depends on your use case of delegation since the parameters are dependant on the type of token you need to obtain. The method `refreshToken` is for using auth0's refresh token and nothing else, that's why the other `delegation` method exists.

The new method's docs has a bit of doc of what each parameter is https://github.com/auth0/react-native-auth0/blob/master/authentication/api.js#L112, since you only need `firebase` the api parameter should be `firebase` and use the user's token instead of the refresh_token. 

I'd suggest contacting [support](https://support.auth0.com) to get a faster response.
