### ISSUE TITLE
`WebAuth.clearSession()` only works on iOS

### ISSUE THREAD

**Issue by DomKM** [auth0/react-native-auth0#91]
It appears that `WebAuth`'s  `.clearSession()` method only works on iOS. When will an Android-compatible implementation be provided? 

Is `.clearSession()`'s platform check (https://github.com/auth0/react-native-auth0/blob/493ed739329e45b1aab031cee719eee67af58adb/webauth/index.js#L112) even necessary? There is no such check in `.authorize()` and that works fine on Android.

**Comment by cocojoe** [comment]
Well the check is necessary, as you just pointed out there is no Android equivalent.  I don't have a timeline as the situation is not as straightforward with multiple potential browsers.

**Comment by DomKM** [comment]
@cocojoe In the mean time, how would you recommend logging out on Android?

**Comment by cocojoe** [comment]
It basically calls a URL, which is detailed here: https://auth0.com/docs/logout
It clears the SSO from the WebAuth, in our sample code upon clearing the browser we also clear any stored tokens https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login

**Comment by DomKM** [comment]
Okay. To clarify, when I refer to "logging out," I am referring to clearing the web session, not dealing `AsyncStorage` or any other type of local storage in which we might store tokens. Sorry for not being clear.

If you use the same logout URL for both iOS and Android, why doesn't `.clearSession()` without the platform check work for this? Is the issue that the user on Android might use different browsers in `.authorize()` and `.clearSession()`, like logging in with Chrome and then trying to logout with Firefox?

**Comment by cocojoe** [comment]
I'm not an Android guy, although I recall it has been discussed internally and a solid consistent solution was not possible. In iOS you have consistency with `SFSafariViewController`, this is not the case in Android as you said different browsers, different sets of cookies. 

Also the platformcheck is there because there is no corresponding code in the underlying Auth0 Android Lib.  Given the above situation.

**Comment by spiralman** [comment]
I just ran into this as well. I'm confused as to why Android supporting multiple browsers is an issue here, especially as I've used lots of Android apps which seem to be able to implement this functionality just fine. Also, it appears that your Android code is using Chrome Custom Tabs, which, as far as I understand, means Chrome will *always* be used, regardless of the user's default browser selection.

I'm also confused as to what "underlying code" is missing in the Android lib? Neither the iOS nor Android libraries have special code for logging in or out, they merely present a browser frame with a given URL (which, in the logout case, is just the log out URL).

As long as the user hasn't switched their default browser between logging out and logging in, this should work without the platform check, which is better than never working at all.

I was able to confirm this by re-implementing the clearSession function manually (note that this code is somewhat hacky, and probably doesn't support all the options as the built in code, but exists as a proof of concept that this is, indeed, possible):

```javascript
    // where this.auth0 is the instance of `Auth0` created when following the normal instructions

    const logoutUrl = this.auth0.auth.logoutUrl({
      returnTo: '[CALLBACK_URL_REGISTERED_IN_ANDROID_MANIFEST]',
      clientId: this.auth0.options.clientId
    });
    return this.auth0.webAuth.agent.show(logoutUrl, true);
```

Please consider re-opening this ticket. This is critical functionality to the operation of this library, and the entire point of using React Native is to get cross-platform support for common functionality.

**Comment by cocojoe** [comment]
@lbalmaceda I feel we should deprecate this method, it had good intentions but the /logout story is not ideal. The recommended story now is to use `prompt=login` and we can promote that in the docs.

@spiralman Please take a look at https://github.com/auth0/react-native-auth0/issues/114#issuecomment-351092213

**Comment by lbalmaceda** [comment]
@cocojoe Yes I agree.
@spiralman "Chrome Custom Tabs" provides of a service interface that many browsers implement. i.e. some samsung browser or firefox. I don't know the internals of using it directly from the custom tab builder class, but it should always prioritize the use of a CC compatible browser previously selected by the user. If no CC compatible browser is found, then the default browser would be used.

**Comment by spiralman** [comment]
@cocojoe I'm not sure what's not ideal about the "`/logout` story", other than the fact that you're disabling it on Android when it should work perfectly well? It seems like forcing a login prompt every time, rather than relying on the OS's stored user session state, is less ideal than correctly implementing logout on the user's request (keeping in mind that, when they click "logout" they haven't actually done anything, which subverts their expectations and could even be a security vulnerability if they really need to clear cookies/tokens off their device).

@lbalmaceda Even if the Custom Tabs interface has been overridden to be not-Chrome, it's still a separate browser from the user's "Default" browser, so won't change when the default browser changes. When they don't have support for Custom Tabs (assuming React Native would even work on that device, since it has it's own API compatibility rules), how likely is it that the default browser will really change between logging in and logging out?

It seems like the chances of running into the case you're worried about are infinitesimally small, and, if you were to hit that case, the logout workflow would fail, and the promise would get rejected, so that user application could correctly handle the error case, anyway. (I should note that this can *always* fail for any number of reasons, even on iOS: the user could have cleared cookies, the device could be offline, Auth0 or the IdP could be down, etc, etc, so the application will always need to handle logout failures, anyway).

**Comment by cocojoe** [comment]
@spiralman sorry, perhaps I should have made this clearer, forcing a login prompt every time of course does not make sense. So let's imagine a user has `logged in` to your application and you have their AT (accessToken). If the user wants to `logout` you clear their AT and set a flag so that the next time you launch WebAuth you will force the prompt.
There is no additional endpoint call to `/logout` required and in iOS 11 with SFAuthenticationSession  this also requires the user to confirm they want to open the browser.

However, ultimately this is an open source library, if you find a solution that works 100% for your particular use case then please feel free to fork and use this.

**Comment by spiralman** [comment]
@cocojoe I understand what you're saying about storing the flag, and not having to force a login each time.

However, my bigger concern is that, without logging out, the user isn't clearing any cookies that are set in the browser session, which could grant access to resources. This is especially troubling on Android, where, through the use of Chrome, the cookies are shared between the application tab and the normal browser.

Consider the following scenario:

1. A user needs to grant access to their phone to an untrusted third party (security checkpoint, your boss, whomever: "the attacker")
1. The user "logs out" of an application using the React Native Auth0 bindings (but, they haven't actually logged out, because log out isn't implemented).
1. The attacker opens a browser window and navigates to the Auth0 signing page for the application.
1. Because the cookies are set in the browser, and the attacker bypassed the application's "force login" flag, they aren't prompted for a login, and are immediately redirected to the app's login callback URL
1. The attacker now has access to the app, which the user explicitly logged out of.

This seems to subvert the user's expectation of security when they think they've logged out of the application, inadvertently opening themselves to an attack vector. Is there some other protection against this attack that I'm missing?

WRT forking your library: that would generate ongoing work for us, keeping our fork in sync with your master (and would your support team offer us support if we were using a forked version of your library?) It seems like suggesting that your customers maintain forks of your product wouldn't be in your best interest.

At the very least, this limitation should be documented up front. Given that there are only two operations in this library (log in, log out), and it only supports two platforms (Android, iOS), you're essentially shipping a library in which 25% of the functionality is broken.

**Comment by lbalmaceda** [comment]
The steps you listed don't succeed as you say. First the _attacker_ would need to have access to your phone (say it's a malicious app). They would also need to know the Authorize URL, which even if the information set in it is public, it's generated from your app and opened directly on the browser so they would need to tamper between both apps. Say they can and they open the browser, go to the URL and are prompted with the "you've previously logged in with.." button. If they click it they are still going to be redirected to the callback URL of your app, since they can't change it just like that as it's a whitelisted parameter in your auth0 dashboard, and changing it in the authorize URL without whitelisting it first would result in an error page being shown. Now your app opens but because it knows there was no previously requested authentication, this "result" is ignored. Your app should handle this state.

Now think of an app that has an intent filter just like the one defined in your app. When the callback URL is hit, the OS would prompt the user to choose between "My app" or "My malicious app" to fulfill the request. This particular case could be completely avoided using the deep-link [domain verification feature](https://developer.android.com/training/app-links/verify-site-associations.html) introduced on android a few years ago.

If you're still not convinced, the authentication in native platforms must follow a PKCE flow which adds a challenge parameter generated from a secure value that never leaves the app that originated it. The idea is that the server can return, in response to the provider authentication, a code that along with this original secure value can be exchanged for auth0 credentials later. You can read more about it [here](https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce).

Like @cocojoe said "logout" in android is tricky because there can be many browser apps installed and you as a dev can't know for sure which one the user is using to access this particular authentication provider (facebook, google, etc). AFAIK browsers don't have a way for an external app to call and clear the cookies, just like that. It's not like iOS where this credentials are handled by Safari. Even if you could some of this providers require the original "provider access_token" to be passed as a parameter when calling /logout, and that access_token is stored in the given auth0 user profile in the identities array but can only be read with the right permissions. This means that from any native platform **you can not securely read them** and so the log out should be handled in a different way. And I'm not even mentioning that you as "My app" shouldn't be logging out the user from the sites they chose to visit. If an app does that without my consent I would automatically uninstall it 😄

So it seems that the only option left for this to "work" is adding that `prompt=login` parameter in the authorize URL.
