### ISSUE TITLE
hide url bar

### ISSUE THREAD

**Issue by Franklin62120** [auth0/react-native-auth0#98]
Hi, 
Is it possible to hide url bar using "auth0.webAuth" form ? 

Thanks in advance

**Comment by cocojoe** [comment]
In which native platform? In iOS this is handled by `SFSafariViewController` which does not provide any functionality to do so.

**Comment by Franklin62120** [comment]
I'm on Android. Is something exist to handle it on Android ?

**Comment by cocojoe** [comment]
Not sure, let me ask @lbalmaceda

**Comment by lbalmaceda** [comment]
The URL cannot be hidden when using CCT. This is by design so users know every time where they are at. 
![image](https://user-images.githubusercontent.com/3900123/31099037-0e5c017c-a79b-11e7-9747-10eee31b8b5b.png)

**Comment by lauracbryson** [comment]
Hi @lbalmaceda - we're building a mobile app using a browser-based URL and have a similar issue of an unattractive URL appearing at the top when users login or sign up to our app. Is there still no way to hide the URL?

**Comment by lbalmaceda** [comment]
@lauracbryson No, "Chrome Custom Tabs" doesn't allow one to hide the URL. As mentioned before this is by design so the user is aware at any time **where** they are navigating and typing sensitive stuff like a password or secret.

There's a new component for android called [Trusted Web Activities](https://developers.google.com/web/updates/2019/02/using-twa) but it's not something I have looked into lately nor a priority for us today.

**Comment by rravithejareddy** [comment]
But @lbalmaceda hiding an URL is useful, because it unnecessarily shows user to logging from browser, small hide make big impact.

**Comment by poovamraj** [comment]
@rravithejareddy we have recently introduced Trusted Web Activity in Android - https://github.com/auth0/Auth0.Android/pull/631

You can check this out and give us your feedback

**Comment by rravithejareddy** [comment]
@poovamraj  can't I use login API's?

**Comment by poovamraj** [comment]
You can use embedded login as well. For universal login, TWA is the only way to achieve native feel
